import {StyleSheet,Dimensions, Button} from 'react-native';
const {width,height} = Dimensions.get('screen');
export const stylesXs = StyleSheet.create({
    backgroud:{
        width:width,
        height:height,
        backgroundColor:'#e8e8e8'
    },
    content:{
    },
    contentmonth:{
        width:width,
        alignItems:'center',
        justifyContent:'center'
    },
    menu:{
        marginTop:height*0.02,
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
    },
    menu3:{
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
    },
    menu1:{
        flexDirection:'row',
        borderRadius:5,
        backgroundColor:'#ffffff',
        width:width*0.42,
        paddingTop:height*0.015,
        paddingBottom:height*0.015,
    },
    menu1active:{
        backgroundColor:'#ffffff',
        width:width*0.42,
        height:'auto',
        minHeight:0,
        maxHeight:height*0.4,
    },
    menu2active:{
        backgroundColor:'#ffffff',
        width:width*0.42,
        height:height*0.2,
        padding:height*0.015,
    },
    menu2:{
        flexDirection:'row',
        borderRadius:5,
        marginLeft:width*0.04,
        backgroundColor:'#ffffff',
        width:width*0.42,
        paddingTop:height*0.015,
        paddingBottom:height*0.015,
    },
    btnmenu:{
        position:'absolute',
        top:width*0.02,
        right:width*0.02,
    },
    radiobtn:{
        borderRadius:5,
        width:width*0.88,
        paddingTop:height*0.015,
        paddingBottom:height*0.015,
        backgroundColor:'#ffffff',
        alignItems:'center',
        marginTop:height*0.02,
        flexDirection:'row',
        justifyContent:'center'
    },
    month:{
        paddingLeft:width*0.05,
        backgroundColor:'#ffffff',
        width:width*0.76,
    },
    search:{
        borderRadius:5,
        width:width*0.88,
        paddingTop: Platform.OS === 'ios' ? 15 : 0,
        paddingBottom:Platform.OS === 'ios' ? 15 : 0,
        backgroundColor:'#ffffff',
        alignItems:'center',
        marginTop:height*0.02,
        flexDirection:'row',
        justifyContent:'center'
    },
    table:{
        marginTop:height*0.04,
        marginBottom:height*0.1,
    },
    edit:{
        paddingLeft:width*0.05,
        backgroundColor:'#ffffff',
        width:width*0.76,
        fontSize:16,
    },
    btn:{
        backgroundColor:'#ffffff',
        width:width*0.12,
        alignItems:'center'
    },
    textmenu:{
        justifyContent:'center',
        paddingLeft:width*0.05,
    },
    text:{
        fontSize:16,
        fontWeight:'500'
    },
    scroll:{
        marginBottom:height*0.01,
    }
})